volumes:
  timetable_local_postgres_data: {}
  timetable_local_postgres_data_backups: {}
  timetable_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: website_local_django
    container_name: website_local_django
    volumes:
      - /app
    working_dir: /app
    env_file:
      - ./.envs/.django
    ports:
      - '8000:8000'
    command: /start
